"""backend/core/compose.py

Builds and merges Docker Compose fragments.

Each deployed service has its own fragment stored at:
  {data_dir}/compose/{key}.yaml

The final docker-compose.yml is produced by merging all active fragments.
This means adding or removing a service is surgical — no regenerating
the whole stack from scratch.

The Traefik fragment is special: it's generated by the platform wizard
and always included. All other fragments are generated from manifests.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from backend.core.config import config
from backend.core.logging import get_logger
from backend.core.state import StateDB

log = get_logger(__name__)

STACK_NETWORK = "mediastack"


# ---------------------------------------------------------------------------
# Fragment builders
# ---------------------------------------------------------------------------


# Environment variables required by each DNS provider for ACME DNS-01 challenge.
# Traefik reads these from its own container environment.
_PROVIDER_ENV_VARS: dict[str, list[str]] = {
    "cloudflare":   ["CF_DNS_API_TOKEN"],
    "route53":      ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_REGION",
                     "AWS_HOSTED_ZONE_ID"],
    "namecheap":    ["NAMECHEAP_API_USER", "NAMECHEAP_API_KEY"],
    "porkbun":      ["PORKBUN_API_KEY", "PORKBUN_SECRET_API_KEY"],
    "digitalocean": ["DO_AUTH_TOKEN"],
    "gandi":        ["GANDI_PERSONAL_ACCESS_TOKEN"],
    "hetzner":      ["HETZNER_API_KEY"],
    "linode":       ["LINODE_TOKEN"],
    "ovh":          ["OVH_ENDPOINT", "OVH_APPLICATION_KEY",
                     "OVH_APPLICATION_SECRET", "OVH_CONSUMER_KEY"],
    "godaddy":      ["GODADDY_API_KEY", "GODADDY_API_SECRET"],
    "duckdns":      ["DUCKDNS_TOKEN"],
    "desec":        ["DESEC_TOKEN"],
    "njalla":       ["NJALLA_TOKEN"],
    "inwx":         ["INWX_USERNAME", "INWX_PASSWORD"],
    "infomaniak":   ["INFOMANIAK_ACCESS_TOKEN"],
    # Additional providers
    "azure":        ["AZURE_CLIENT_ID", "AZURE_CLIENT_SECRET",
                     "AZURE_SUBSCRIPTION_ID", "AZURE_RESOURCE_GROUP"],
    "google":       ["GCE_PROJECT", "GCE_SERVICE_ACCOUNT_FILE"],
    "vultr":        ["VULTR_API_KEY"],
    "bunny":        ["BUNNY_API_KEY"],
    "dnspod":       ["DNSPOD_API_KEY", "DNSPOD_SECRET_ID"],
}


# ── Docker Compose command helper ─────────────────────────────────────────


def compose_up(frag_path: "Path", pull: bool = True, timeout: int = 120) -> tuple[int, str]:
    """Run `docker compose up -d` for a fragment, always passing the shared .env file.

    Returns (returncode, error_output).
    The --env-file flag ensures env vars (CF_DNS_API_TOKEN, etc.) resolve
    correctly regardless of the working directory compose is called from.
    """
    import subprocess as _sp
    from backend.core.config import config as _cfg
    cmd = [
        "docker", "compose",
        "-f", str(frag_path),
        "--env-file", str(_cfg.env_file),
        "up", "-d",
    ]
    if pull:
        cmd += ["--pull", "missing"]
    r = _sp.run(cmd, capture_output=True, text=True, timeout=timeout)
    return r.returncode, (r.stderr or r.stdout).strip()


def compose_down(frag_path: "Path", timeout: int = 60) -> tuple[int, str]:
    """Run `docker compose down` for a fragment, always passing the shared .env file."""
    import subprocess as _sp
    from backend.core.config import config as _cfg
    cmd = [
        "docker", "compose",
        "-f", str(frag_path),
        "--env-file", str(_cfg.env_file),
        "down", "--remove-orphans",
    ]
    r = _sp.run(cmd, capture_output=True, text=True, timeout=timeout)
    return r.returncode, (r.stderr or r.stdout).strip()


def build_traefik_fragment(
    domain: str,
    config_root: str,
    network_name: str = STACK_NETWORK,
    cert_resolver: str = "letsencrypt",
    dns_provider: str = "cloudflare",
) -> dict[str, Any]:
    """Generate the Traefik service compose fragment.

    Passes all environment variables required by the configured DNS provider
    so Traefik can complete the DNS-01 ACME challenge.
    Non-CF providers (Route53, Namecheap, Porkbun, etc.) previously received
    no env vars and cert issuance would silently fail.
    """
    traefik_config_path = f"{config_root}/traefik"
    acme_path = f"{traefik_config_path}/acme.json"
    # ZeroSSL uses a separate storage file — must be mounted so it persists
    acme_zerossl_path = f"{traefik_config_path}/acme-zerossl.json"

    # Build env dict for the selected DNS provider
    provider_vars = _PROVIDER_ENV_VARS.get(dns_provider, [])
    env = {var: f"${{{var}}}" for var in provider_vars}

    # Read image tag and dashboard port from settings
    try:
        from backend.core.state import StateDB as _SDB
        with _SDB() as _db:
            _tag = _db.get_setting("traefik_image_tag") or "v3.2"
            _port = int(_db.get_setting("traefik_dashboard_port") or "8081")
    except Exception:
        _tag, _port = "v3.2", 8081

    return {
    "image": f"traefik:{_tag}",
        "container_name": "traefik",
        "restart": "unless-stopped",
        "networks": [network_name],
        "ports": [
            "80:80",
            "443:443",
            f"127.0.0.1:{_port}:8080",  # dashboard — localhost only until auth deployed
        ],
        "volumes": [
            "/var/run/docker.sock:/var/run/docker.sock:ro",
            f"{traefik_config_path}/traefik.yml:/traefik.yml:ro",
            f"{acme_path}:/acme.json",
f"{acme_zerossl_path}:/acme-zerossl.json",  # ZeroSSL fallback resolver
            f"{traefik_config_path}/acme-buypass.json:/acme-buypass.json",  # Buypass CA
        ],
        "environment": env,
        "labels": [
            "traefik.enable=true",
            f"traefik.http.routers.traefik.rule=Host(`traefik.{domain}`)",
            "traefik.http.routers.traefik.entrypoints=websecure",
            "traefik.http.routers.traefik.tls=true",
            f"traefik.http.routers.traefik.tls.certresolver={cert_resolver}",
            "traefik.http.routers.traefik.service=api@internal",
            # traefik-auth middleware added by wizard when auth infra slot is deployed
        ],
    }


def build_traefik_yaml(
    domain: str,
    cert_resolver: str = "letsencrypt",
    acme_email: str = "",
    dns_provider: str = "cloudflare",
    include_zerossl: bool = True,
    eab_kid: str = "",
    eab_hmac: str = "",
) -> str:
    """Generate the traefik.yml static config content.

    Uses DNS-01 challenge exclusively — this is the only challenge type
    that supports wildcard certificates (*.domain.com) and works without
    any open ports, which is required for media server direct access.

    Both letsencrypt and zerossl resolvers are configured. ZeroSSL is
    a useful fallback if Let's Encrypt rate limits are hit during setup.

    Supported dns_provider values (via Traefik/lego):
      cloudflare, route53, namecheap, porkbun, digitalocean, gandi,
      duckdns, dynu, hetzner, linode, ovh, godaddy, njalla, namecheap,
      google, azure, desec, infomaniak, and 80+ more.
      Full list: https://doc.traefik.io/traefik/https/acme/#providers
    """
    email = acme_email or f"admin@{domain}"
    # Build ZeroSSL EAB block only when credentials are provided
    if eab_kid and eab_hmac:
        _eab_block = f"      eab:\n        kid: {eab_kid}\n        hmacEncoded: {eab_hmac}"
    else:
        _eab_block = ""

    if include_zerossl or cert_resolver == "zerossl":
        _eab_section = f"\n{_eab_block}" if _eab_block else ""
        zerossl_block = (
            f"\n  zerossl:\n"
            f"    acme:\n"
            f"      email: {email}\n"
            f"      caServer: https://acme.zerossl.com/v2/DV90\n"
            f"      storage: /acme-zerossl.json{_eab_section}\n"
            f"      dnsChallenge:\n"
            f"        provider: {dns_provider}\n"
            f"        resolvers:\n"
            f'          - "1.1.1.1:53"\n'
            f'          - "8.8.8.8:53"\n'
        )
    else:
        zerossl_block = ""

    # Buypass: free browser-trusted CA, 180-day certs, no EAB required.
    # Independent rate limits from Let's Encrypt. Good fallback or primary choice.
    if cert_resolver == "buypass" or (include_zerossl and cert_resolver != "staging"):
        buypass_block = (
            f"\n  buypass:\n"
            f"    acme:\n"
            f"      email: {email}\n"
            f"      caServer: https://api.buypass.com/acme/directory\n"
            f"      storage: /acme-buypass.json\n"
            f"      dnsChallenge:\n"
            f"        provider: {dns_provider}\n"
            f"        resolvers:\n"
            f'          - "1.1.1.1:53"\n'
            f'          - "8.8.8.8:53"\n'
        )
    else:
        buypass_block = ""

    return f"""\
# Traefik static configuration — managed by Mediastack
# Do not edit manually; re-run the platform wizard to regenerate.
# DNS-01 challenge: no open ports needed for cert issuance.
# Wildcard cert (*.{domain}) covers every app subdomain automatically.

global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO

api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        # Wildcard cert applied globally — every subdomain gets HTTPS
        # automatically without per-app certificate configuration.
        certResolver: {cert_resolver}
        domains:
          - main: "*.{domain}"
            sans:
              - "{domain}"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: {STACK_NETWORK}
  file:
    directory: /config/traefik/dynamic
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: {email}
      storage: /acme.json
      dnsChallenge:
        provider: {dns_provider}
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
        # 30s delay before checking propagation — needed on some DNS providers
        # Increase to 60s if cert issuance fails with propagation errors.
        delayBeforeCheck: 30s
{zerossl_block}{buypass_block}"""


# System-reserved host ports that Traefik or Mediastack already own —
# apps whose internal port matches one of these can't bind a host port,
# they're reachable via Traefik hostname routing only.
#   80/443 → Traefik HTTP/HTTPS,  8080 → Mediastack UI,  8081 → Traefik dashboard
_SYSTEM_PORTS: frozenset[int] = frozenset({80, 443, 8080, 8081})

# Optional fragment keys whose values must be `list()`-copied before
# being set on the fragment dict (snapshot semantics — see
# build_service_fragment).
_FRAGMENT_LIST_KEYS: frozenset[str] = frozenset({"cap_add", "security_opt", "devices"})


def _frag_env(linuxserver: bool, puid: int, pgid: int, timezone: str,
              static_env: dict[str, str] | None,
              env_overrides: dict[str, str] | None) -> dict[str, str]:
    """Assemble the `environment:` block.
    Order: linuxserver PUID/PGID/TZ → static_env → env_overrides (escaped).
    Override order matches the original (overrides win)."""
    env: dict[str, str] = {}
    if linuxserver:
        env["PUID"] = str(puid)
        env["PGID"] = str(pgid)
        env["TZ"] = timezone
    if static_env:
        env.update(static_env)
    if env_overrides:
        env.update({k: _esc(str(v)) for k, v in env_overrides.items()})
    return env


def _frag_volumes(config_path: str, media_root: str | None,
                  extra_volumes: list[dict[str, str]] | None) -> list[str]:
    """Assemble the `volumes:` block. `/config` always present;
    `/data` added when media_root is set; extra_volumes appended raw."""
    volumes = [f"{config_path}:/config"]
    if media_root:
        volumes.append(f"{media_root}:/data")
    if extra_volumes:
        for vol in extra_volumes:
            ro = ":ro" if vol.get("readonly") else ""
            volumes.append(f"{vol['host']}:{vol['container']}{ro}")
    return volumes


def _frag_ports(web_port: int | None, host_port: int | None) -> list[str]:
    """Assemble the `ports:` block. Empty list if web_port lands on a
    system-reserved port (Traefik / Mediastack ownership) or when
    either port is unset."""
    if web_port and host_port and web_port not in _SYSTEM_PORTS:
        return [f"{host_port}:{web_port}"]
    return []


def _frag_healthcheck(web_port: int | None,
                      start_grace_s: int) -> dict[str, Any] | None:
    """Docker-level healthcheck with `start_period` so Docker doesn't
    restart the container during its boot window. None when no web
    port is exposed or no start grace is configured — the absence of
    a healthcheck section is the canonical 'no Docker-level check'."""
    grace = start_grace_s or 0
    if not (web_port and grace > 0):
        return None
    return {
        "test": [
            "CMD-SHELL",
            f"wget -qO- http://localhost:{web_port}/ > /dev/null 2>&1 || exit 1",
        ],
        "interval": "30s",
        "timeout": "10s",
        "retries": 3,
        "start_period": f"{grace}s",
    }


def build_service_fragment(
    manifest_key: str,
    display_name: str,
    image: str,
    image_tag: str,
    web_port: int | None,
    host_port: int | None,
    config_path: str,
    media_root: str | None,
    domain: str,
    network_name: str = STACK_NETWORK,
    puid: int = 1000,
    pgid: int = 1000,
    timezone: str = "UTC",
    linuxserver: bool = True,
    env_overrides: dict[str, str] | None = None,
    static_env: dict[str, str] | None = None,
    cert_resolver: str = "letsencrypt",
    lan_subnet: str | None = None,
    tinyauth_enabled: bool = False,
    extra_volumes: list[dict[str, str]] | None = None,
    capabilities: list[str] | None = None,
    security_opt: list[str] | None = None,
    devices: list[str] | None = None,
    shm_size: str | None = None,
    service_type: str = "management",
    start_grace_s: int = 0,
) -> dict[str, Any]:
    """Build a service compose fragment from manifest data.

    Step 2.7.e: extracts environment / volumes / ports / healthcheck
    phases into helpers (`_frag_env`, `_frag_volumes`, `_frag_ports`,
    `_frag_healthcheck`) and assembles the optional fragment keys via
    a (key, value) table loop — drops complexity from 17 to ≤ 4.
    """
    fragment: dict[str, Any] = {
        "image": f"{image}:{image_tag}",
        "container_name": manifest_key,
        "restart": "unless-stopped",
        "networks": [network_name],
    }

    # Management labels always present (ADR 0017 §D): purge/clean enumeration depends on them.
    _labels: list[str] = [
        "mediastack.managed=true",
        f"mediastack.app-key={manifest_key}",
    ]
    _labels.extend(_traefik_labels(
        key=manifest_key, domain=domain, web_port=web_port,
        cert_resolver=cert_resolver, lan_subnet=lan_subnet,
        tinyauth_enabled=tinyauth_enabled,
    ))
    fragment["labels"] = _labels

    optional: list[tuple[str, Any]] = [
        ("environment", _frag_env(linuxserver, puid, pgid, timezone,
                                  static_env, env_overrides)),
        ("volumes",     _frag_volumes(config_path, media_root, extra_volumes)),
        ("ports",       _frag_ports(web_port, host_port)),
        ("cap_add",     capabilities),
        ("security_opt", security_opt),
        ("devices",     devices),
        ("shm_size",    shm_size),
        ("healthcheck", _frag_healthcheck(web_port, start_grace_s)),
    ]
    for key, value in optional:
        if value:
            fragment[key] = list(value) if key in _FRAGMENT_LIST_KEYS else value
    return fragment


def _traefik_labels(
    key: str,
    domain: str,
    web_port: int | None,
    cert_resolver: str,
    lan_subnet: str | None,
    tinyauth_enabled: bool,
) -> list[str]:
    if not web_port:
        return []

    subdomain = f"{key}.{domain}"
    base = [
        "traefik.enable=true",
        f"traefik.http.services.{key}.loadbalancer.server.port={web_port}",
        # TLS wildcard cert
        f"traefik.http.routers.{key}.tls=true",
        f"traefik.http.routers.{key}.tls.certresolver={cert_resolver}",
        f"traefik.http.routers.{key}.tls.domains[0].main={domain}",
        f"traefik.http.routers.{key}.tls.domains[0].sans=*.{domain}",
    ]

    if tinyauth_enabled and lan_subnet:
        # Two-router pattern: LAN bypasses auth, internet hits Tinyauth
        base += [
            # LAN router (high priority, no auth)
            f"traefik.http.routers.{key}-lan.rule=Host(`{subdomain}`) && ClientIP(`{lan_subnet}`)",
            f"traefik.http.routers.{key}-lan.entrypoints=websecure",
            f"traefik.http.routers.{key}-lan.priority=10",
            f"traefik.http.routers.{key}-lan.tls=true",
            f"traefik.http.routers.{key}-lan.tls.certresolver={cert_resolver}",
            f"traefik.http.routers.{key}-lan.service={key}",
            # Catch-all router (lower priority, Tinyauth middleware)
            f"traefik.http.routers.{key}.rule=Host(`{subdomain}`)",
            f"traefik.http.routers.{key}.entrypoints=websecure",
            f"traefik.http.routers.{key}.priority=5",
            f"traefik.http.routers.{key}.middlewares=tinyauth-auth@docker",
            f"traefik.http.routers.{key}.service={key}",
        ]
    else:
        base += [
            f"traefik.http.routers.{key}.rule=Host(`{subdomain}`)",
            f"traefik.http.routers.{key}.entrypoints=websecure",
            f"traefik.http.routers.{key}.service={key}",
        ]

    return base


def _esc(value: str) -> str:
    """Escape $ in user-supplied values so Docker Compose doesn't interpolate them."""
    if not value:
        return value
    if value.startswith("${") and value.endswith("}"):
        return value   # intentional placeholder — leave as-is
    return value.replace("$", "$$")


# ---------------------------------------------------------------------------
# Fragment persistence
# ---------------------------------------------------------------------------


def write_fragment(key: str, service_def: dict[str, Any],
                   network_name: str = STACK_NETWORK) -> Path:
    """Write a service compose fragment to disk.

    Includes a top-level networks: external declaration so each fragment can
    be run standalone with docker compose -f key.yaml up -d without Compose
    complaining that the network is undefined.
    """
    fragment_dir = config.compose_dir
    fragment_dir.mkdir(parents=True, exist_ok=True)

    path = fragment_dir / f"{key}.yaml"
    content = {
        "services": {key: service_def},
        "networks": {network_name: {"external": True}},
    }
    path.write_text(yaml.dump(content, default_flow_style=False, sort_keys=False))
    log.debug("Wrote compose fragment: %s", path)
    return path


def remove_fragment(key: str) -> None:
    """Remove a service compose fragment."""
    path = config.compose_dir / f"{key}.yaml"
    if path.exists():
        path.unlink()
        log.info("Removed compose fragment: %s", path)


def merge_fragments(network_name: str = STACK_NETWORK) -> str:
    """Merge all active fragments into a single docker-compose.yml string."""
    fragment_dir = config.compose_dir
    if not fragment_dir.exists():
        return ""

    merged: dict[str, Any] = {
        "networks": {
            network_name: {"external": True},
        },
        "services": {},
    }

    for frag_path in sorted(fragment_dir.glob("*.yaml")):
        try:
            frag = yaml.safe_load(frag_path.read_text()) or {}
            services = frag.get("services", {})
            merged["services"].update(services)
        except yaml.YAMLError as e:
            log.warning("Skipping malformed fragment %s: %s", frag_path.name, e)

    return yaml.dump(merged, default_flow_style=False, sort_keys=False)


def write_compose_file(output_path: Path, network_name: str = STACK_NETWORK) -> Path:
    """Write the merged docker-compose.yml to disk."""
    content = merge_fragments(network_name)
    output_path.write_text(content)
    log.info("Wrote docker-compose.yml: %s", output_path)
    return output_path


def build_socket_proxy_fragment() -> dict[str, Any]:
    """Build compose fragment for Tecnativa docker-socket-proxy.

    The proxy sits between Traefik and the Docker socket, restricting
    Traefik to read-only API calls only. This prevents Traefik from
    executing arbitrary Docker operations even if compromised.

    Traefik is configured to use this proxy instead of the raw socket.
    """
    return {
        "image": "tecnativa/docker-socket-proxy:latest",
        "container_name": "docker-socket-proxy",
        "environment": {
            # Allowlist: only what Traefik needs
            "CONTAINERS": "1",
            "SERVICES": "1",
            "NETWORKS": "1",
            "TASKS": "1",
            # Deny everything else
            "EVENTS": "1",
            "INFO": "1",
            "VOLUMES": "0",
            "IMAGES": "0",
            "AUTH": "0",
            "POST": "0",
            "DELETE": "0",
        },
        "volumes": [
            "/var/run/docker.sock:/var/run/docker.sock:ro",
        ],
        "expose": ["2375"],
        "restart": "unless-stopped",
        "security_opt": ["no-new-privileges:true"],
    }
