#!/usr/bin/env python3
"""
Mediastack 1.1.5 cleanup + pre-work (TODO #1/#2/#3)
Run as: python3 /tmp/ms_115_cleanup.py
Must be run as the stack user from any directory.
"""
import os, re, subprocess, sys
from pathlib import Path

REPO = Path("/srv/mediastack")
os.chdir(REPO)
COMMITS = {}   # label -> sha

# ── helpers ──────────────────────────────────────────────────────────────────

def run(cmd, check=True, capture=True):
    r = subprocess.run(cmd, shell=True,
                       capture_output=capture, text=True, cwd=str(REPO))
    if check and r.returncode != 0:
        print(f"\n❌  FAILED: {cmd}")
        if r.stdout: print(r.stdout[-2000:])
        if r.stderr: print(r.stderr[-2000:])
        sys.exit(1)
    return r

def heading(text):
    print(f"\n{'='*60}")
    print(f"  {text}")
    print('='*60)

def ok(text): print(f"  ✓  {text}")
def info(text): print(f"  →  {text}")
def warn(text): print(f"  ⚠  {text}")

def git_commit(label, msg):
    run('git add -A')
    r = run(f'git commit -m "{msg}"', check=False)
    if r.returncode != 0:
        if 'nothing to commit' in r.stdout + r.stderr:
            warn(f"Nothing to commit for {label}")
            sha = run("git rev-parse --short HEAD").stdout.strip()
        else:
            print(r.stdout); print(r.stderr); sys.exit(1)
    sha = run("git rev-parse --short HEAD").stdout.strip()
    COMMITS[label] = sha
    ok(f"Committed {label}: {sha}")
    return sha

def remove_commit_lines(path: Path) -> int:
    """Remove lines containing ._c.commit() (excluding self._c.commit()).
    Returns number of lines removed."""
    text = path.read_text()
    lines = text.splitlines(keepends=True)
    new_lines = []
    removed = 0
    for line in lines:
        if '._c.commit()' in line and 'self._c.commit()' not in line:
            removed += 1
            info(f"  Removing: {line.rstrip()!r}")
        else:
            new_lines.append(line)
    if removed:
        path.write_text(''.join(new_lines))
    return removed

def run_enforce():
    info("Running ms-enforce --fast ...")
    r = run("python3 tools/ms-enforce.py --fast", check=False)
    print(r.stdout[-3000:] if r.stdout else "")
    if r.returncode != 0:
        warn("ms-enforce --fast returned non-zero (check output above)")
        # Don't hard-fail — Tier 0 has 2 pre-existing violations (j/k) we can't fix yet
    return r.returncode

def run_tests(*test_paths):
    paths = ' '.join(test_paths)
    info(f"Running pytest {paths} ...")
    r = run(f"python3 -m pytest {paths} -v --tb=short -q", check=False)
    print(r.stdout[-4000:] if r.stdout else "")
    if r.returncode != 0:
        print(r.stderr[-2000:] if r.stderr else "")
        warn("Tests failed — inspect above output before continuing")
        ans = input("  Continue anyway? [y/N]: ").strip().lower()
        if ans != 'y':
            sys.exit(1)
    return r.returncode

# ── check identity ────────────────────────────────────────────────────────────
heading("Identity check")
whoami = run("whoami").stdout.strip()
if whoami == "root":
    print("❌  Running as root — commits must be as the stack user. Aborting.")
    sys.exit(1)
ok(f"Running as: {whoami}")
current_commit = run("git rev-parse --short HEAD").stdout.strip()
ok(f"Current commit: {current_commit}")

# ── baseline test ─────────────────────────────────────────────────────────────
heading("BASELINE: pytest tests/test_comprehensive_contracts.py")
info("Expected: 150 passed, 3 pre-existing failures")
run_tests("tests/test_comprehensive_contracts.py")

# ══════════════════════════════════════════════════════════════════════════════
# PRE-WORK: TODO #1 + #2 + #3 (one commit)
# ══════════════════════════════════════════════════════════════════════════════
heading("PRE-WORK: TODO #1 + #2 + #3")

# ── TODO #1: .gitignore ───────────────────────────────────────────────────────
gitignore = REPO / ".gitignore"
gitignore_text = gitignore.read_text()
addon = "\n# Regenerated by tooling on every run\ndata/coverage_map.json\ndata/state.db.bak.*\n"
if "coverage_map.json" not in gitignore_text:
    gitignore.write_text(gitignore_text + addon)
    ok("Added data/coverage_map.json and data/state.db.bak.* to .gitignore")
else:
    ok(".gitignore already has coverage_map.json — skipping")

# Also git rm --cached if tracked
r = run("git ls-files data/coverage_map.json", check=False)
if r.stdout.strip():
    run("git rm --cached data/coverage_map.json", check=False)
    ok("Untracked data/coverage_map.json from git index")

# ── TODO #2: normalize-ownership.sh ──────────────────────────────────────────
norm_sh = REPO / "tools" / "normalize-ownership.sh"
norm_text = norm_sh.read_text()

# Remove the 4 entries from EXCLUDE_PATHS that are wrong
# The lines to remove (exact strings from the file):
wrong_entries = [
    '    "$REPO/.git"            # ms-update already self-heals .git separately\n',
    '    "$REPO/.git"            # ms-update already self-heals .git separately',
    '    "$REPO/.ruff_cache"\n',
    '    "$REPO/.ruff_cache"',
    '    "$REPO/.pytest_cache"\n',
    '    "$REPO/.pytest_cache"',
    '    "$REPO/.hypothesis"\n',
    '    "$REPO/.hypothesis"',
]

norm_new = norm_text
for entry in wrong_entries:
    if entry in norm_new:
        norm_new = norm_new.replace(entry, '')
        ok(f"Removed from normalize-ownership.sh EXCLUDE_PATHS: {entry.strip()!r}")

if norm_new != norm_text:
    norm_sh.write_text(norm_new)
else:
    warn("normalize-ownership.sh: no changes made — entries may already be removed")

# ── TODO #3: ms-update inline .git self-heal block removal ───────────────────
ms_update = REPO / "ms-update"
ms_text = ms_update.read_text()

# Block to remove (the _SVC_USER definition + .git/objects if block)
# We replace it with just the _SVC_USER definition moved to just before normalize call
old_block = """    # 1. Fix .git ownership (sudo creates root-owned objects blocking stack)
    _SVC_USER=$(stat -c "%U" "$REPO" 2>/dev/null || echo "stack")
    if [[ -d "$REPO/.git/objects" ]]; then
        _OBJ_OWNER=$(stat -c "%U" "$REPO/.git/objects" 2>/dev/null || echo "unknown")
        if [[ "$_OBJ_OWNER" != "$_SVC_USER" ]] && [[ "$_OBJ_OWNER" != "unknown" ]]; then
            chown -R "${_SVC_USER}:${_SVC_USER}" "$REPO/.git" 2>/dev/null || true
            echo "  ! Fixed .git ownership → ${_SVC_USER}"
        fi
    fi"""

# The normalize-ownership call to find (add _SVC_USER before it)
norm_call_old = '    if [[ -x "$REPO/tools/normalize-ownership.sh" ]]; then'
norm_call_new = ('    _SVC_USER=$(stat -c "%U" "$REPO" 2>/dev/null || echo "stack")\n'
                 '    if [[ -x "$REPO/tools/normalize-ownership.sh" ]]; then')

ms_new = ms_text
if old_block in ms_new:
    ms_new = ms_new.replace(old_block, "    # 1. .git ownership now handled by normalize-ownership.sh (called at step 6)")
    ok("Replaced inline .git self-heal block in ms-update")
else:
    warn("ms-update: could not find exact block to replace — manual review needed")
    # Try partial match
    if '_SVC_USER=$(stat -c "%U" "$REPO"' in ms_new and '.git/objects' in ms_new:
        warn("Found partial match — skipping to avoid corruption. Edit ms-update manually.")

if norm_call_old in ms_new and '_SVC_USER' not in ms_new.split(norm_call_old)[0].split('\n')[-5:]:
    ms_new = ms_new.replace(norm_call_old, norm_call_new, 1)
    ok("Added _SVC_USER definition before normalize-ownership call in ms-update")

if ms_new != ms_text:
    ms_update.write_text(ms_new)

info("Running normalize-ownership.sh once to fix .git/ and cache dirs ...")
r = run("sudo tools/normalize-ownership.sh", check=False)
if r.returncode == 0:
    ok("normalize-ownership.sh ran successfully")
else:
    warn(f"normalize-ownership.sh returned {r.returncode} (may need sudo)")

# Commit pre-work
git_commit("pre_todo",
    "fix(ops): TODO #1+#2+#3 — gitignore tooling files, normalize-ownership covers .git/caches, remove redundant ms-update inline .git self-heal\n\n"
    "TODO #1: Add data/coverage_map.json and data/state.db.bak.* to .gitignore\n"
    "TODO #2: normalize-ownership.sh no longer excludes .git/, .hypothesis/, .pytest_cache/, .ruff_cache/\n"
    "TODO #3: ms-update inline .git/objects self-heal removed (normalize-ownership.sh handles it)")

# ══════════════════════════════════════════════════════════════════════════════
# 1.1.5.a — backend/api/quickstart.py (3 sites: lines 98, 140, 161)
# ══════════════════════════════════════════════════════════════════════════════
heading("1.1.5.a — backend/api/quickstart.py (3 sites)")
path = REPO / "backend/api/quickstart.py"
n = remove_commit_lines(path)
if n != 3:
    warn(f"Expected 3 removals, got {n} — inspect file before continuing")
    input("Press Enter to continue or Ctrl+C to abort: ")
run_tests("tests/test_state.py")
run_enforce()
git_commit("1.1.5.a",
    "refactor(cleanup): 1.1.5.a remove redundant db._c.commit() from quickstart.py (Core Rule 4.4)\n\n"
    "Removed 3 sites at original lines 98, 140, 161.\n"
    "StateDB.__exit__ auto-commits on clean exit (verified by test_state.py::TestStateDBContextManager::test_autocommit_on_clean_exit, added in 932646e).\n"
    "No behavioral change — redundant no-ops removed.")

# ══════════════════════════════════════════════════════════════════════════════
# 1.1.5.b — backend/core/ai_safety.py (1 site: line 186)
# ══════════════════════════════════════════════════════════════════════════════
heading("1.1.5.b — backend/core/ai_safety.py (1 site)")
path = REPO / "backend/core/ai_safety.py"
n = remove_commit_lines(path)
if n != 1:
    warn(f"Expected 1 removal, got {n}")
    input("Press Enter to continue: ")
run_tests("tests/test_state.py")
run_enforce()
git_commit("1.1.5.b",
    "refactor(cleanup): 1.1.5.b remove redundant db._c.commit() from ai_safety.py (Core Rule 4.4)\n\n"
    "Removed 1 site at original line 186 (execute_action rewire branch).\n"
    "StateDB.__exit__ auto-commits on clean exit.")

# ══════════════════════════════════════════════════════════════════════════════
# 1.1.5.c — backend/core/llm_router.py (3 sites: lines 201, 251, 258)
# ══════════════════════════════════════════════════════════════════════════════
heading("1.1.5.c — backend/core/llm_router.py (3 sites)")
path = REPO / "backend/core/llm_router.py"
n = remove_commit_lines(path)
if n != 3:
    warn(f"Expected 3 removals, got {n}")
    input("Press Enter to continue: ")
run_tests("tests/test_state.py")
run_enforce()
git_commit("1.1.5.c",
    "refactor(cleanup): 1.1.5.c remove redundant db._c.commit() from llm_router.py (Core Rule 4.4)\n\n"
    "Removed 3 sites at original lines 201 (sync_registry_with_files), 251 (upsert_model), 258 (remove_model_from_registry).\n"
    "StateDB.__exit__ auto-commits on clean exit.")

# ══════════════════════════════════════════════════════════════════════════════
# 1.1.5.d — backend/health/checker.py (4 sites: lines 162, 493, 646, 992)
# ══════════════════════════════════════════════════════════════════════════════
heading("1.1.5.d — backend/health/checker.py (4 sites)")
path = REPO / "backend/health/checker.py"
n = remove_commit_lines(path)
if n != 4:
    warn(f"Expected 4 removals, got {n}")
    input("Press Enter to continue: ")
run_tests("tests/test_state.py")
run_enforce()
git_commit("1.1.5.d",
    "refactor(cleanup): 1.1.5.d remove redundant db._c.commit() from checker.py (Core Rule 4.4)\n\n"
    "Removed 4 sites at original lines 162 (_log_routing), 493 (_llm_diagnose pending_fixes), "
    "646 (check_app resolve pending fixes), 992 (_attempt_self_heal rewire).\n"
    "StateDB.__exit__ auto-commits on clean exit.")

# ══════════════════════════════════════════════════════════════════════════════
# 1.1.5.e — backend/health/managed_services.py (2 sites: lines 73, 113)
# ══════════════════════════════════════════════════════════════════════════════
heading("1.1.5.e — backend/health/managed_services.py (2 sites)")
path = REPO / "backend/health/managed_services.py"
n = remove_commit_lines(path)
if n != 2:
    warn(f"Expected 2 removals, got {n}")
    input("Press Enter to continue: ")
run_tests("tests/test_state.py")
run_enforce()
git_commit("1.1.5.e",
    "refactor(cleanup): 1.1.5.e remove redundant db._c.commit() from managed_services.py (Core Rule 4.4)\n\n"
    "Removed 2 sites at original lines 73 (container not running branch), 113 (update managed_services table).\n"
    "StateDB.__exit__ auto-commits on clean exit.")

# ══════════════════════════════════════════════════════════════════════════════
# 1.1.5.f — backend/health/source_checker.py (2 sites: lines 54, 245)
# ══════════════════════════════════════════════════════════════════════════════
heading("1.1.5.f — backend/health/source_checker.py (2 sites)")
path = REPO / "backend/health/source_checker.py"
n = remove_commit_lines(path)
if n != 2:
    warn(f"Expected 2 removals, got {n}")
    input("Press Enter to continue: ")
run_tests("tests/test_state.py")
run_enforce()
git_commit("1.1.5.f",
    "refactor(cleanup): 1.1.5.f remove redundant db._c.commit() from source_checker.py (Core Rule 4.4)\n\n"
    "Removed 2 sites at original lines 54 (_ensure_tables), 245 (run_source_scan _probe).\n"
    "StateDB.__exit__ auto-commits on clean exit.")

# ══════════════════════════════════════════════════════════════════════════════
# 1.1.5.g — backend/infra/registry.py (3 sites: lines 142, 284, 300)
# ══════════════════════════════════════════════════════════════════════════════
heading("1.1.5.g — backend/infra/registry.py (3 sites)")
path = REPO / "backend/infra/registry.py"
n = remove_commit_lines(path)
if n != 3:
    warn(f"Expected 3 removals, got {n}")
    input("Press Enter to continue: ")
run_tests("tests/test_state.py")
run_enforce()
git_commit("1.1.5.g",
    "refactor(cleanup): 1.1.5.g remove redundant db._c.commit() from registry.py (Core Rule 4.4)\n\n"
    "Removed 3 sites at original lines 142 (swap_slot migration insert), 284 (_update_migration), 300 (_complete_migration).\n"
    "StateDB.__exit__ auto-commits on clean exit.")

# ══════════════════════════════════════════════════════════════════════════════
# 1.1.5.h — backend/manifests/executor.py (5 sites: lines 608, 723, 994, 1151, 1222)
# ══════════════════════════════════════════════════════════════════════════════
heading("1.1.5.h — backend/manifests/executor.py (5 sites)")
path = REPO / "backend/manifests/executor.py"
n = remove_commit_lines(path)
if n != 5:
    warn(f"Expected 5 removals, got {n}")
    input("Press Enter to continue: ")
run_tests("tests/test_state.py")
run_enforce()
git_commit("1.1.5.h",
    "refactor(cleanup): 1.1.5.h remove redundant db._c.commit() from executor.py (Core Rule 4.4)\n\n"
    "Removed 5 sites at original lines 608 (_remove_inner unwire), 723 (replace_app rewire), "
    "994 (_wire), 1151 (disable_app), 1222 (enable_app).\n"
    "StateDB.__exit__ auto-commits on clean exit.")

# ══════════════════════════════════════════════════════════════════════════════
# 1.1.5.i — backend/platform/storage.py (3 sites: lines 363, 394, 400)
# ══════════════════════════════════════════════════════════════════════════════
heading("1.1.5.i — backend/platform/storage.py (3 sites)")
path = REPO / "backend/platform/storage.py"
n = remove_commit_lines(path)
if n != 3:
    warn(f"Expected 3 removals, got {n}")
    input("Press Enter to continue: ")
run_tests("tests/test_state.py")
run_enforce()
git_commit("1.1.5.i",
    "refactor(cleanup): 1.1.5.i remove redundant db._c.commit() from storage.py (Core Rule 4.4)\n\n"
    "Removed 3 sites at original lines 363 (add_source), 394 (update_source_status), 400 (remove_source).\n"
    "StateDB.__exit__ auto-commits on clean exit.")

# ══════════════════════════════════════════════════════════════════════════════
# 1.1.5.m — Final ms-enforce --fast check
# ══════════════════════════════════════════════════════════════════════════════
heading("1.1.5.m — Final ms-enforce --fast (Tier 0 bare-db-commit should be 0)")
run_enforce()

# ══════════════════════════════════════════════════════════════════════════════
# Final comprehensive test run
# ══════════════════════════════════════════════════════════════════════════════
heading("Final: pytest tests/test_comprehensive_contracts.py")
info("Expected: 150 passed, 3 pre-existing failures (same as baseline)")
run_tests("tests/test_comprehensive_contracts.py")

# ══════════════════════════════════════════════════════════════════════════════
# 1.1.5.n — Update PROJECT_CLEANUP.md RECORD section
# ══════════════════════════════════════════════════════════════════════════════
heading("1.1.5.n — Updating PROJECT_CLEANUP.md RECORD section")

cleanup_md = REPO / "docs/cleanup/PROJECT_CLEANUP.md"
md_text = cleanup_md.read_text()

# Build the record entry
record_lines = [
    "",
    "**Step 1.1.5 — Core Rule 4.4 cleanup (26 db._c.commit() removals)** — 2026-05-05",
    "",
    "Pre-work commit (TODO #1+#2+#3): " + COMMITS.get("pre_todo", "?"),
    "",
    "| Sub-task | File | Sites | Commit |",
    "|---|---|---|---|",
    f"| 1.1.5.a | backend/api/quickstart.py | 3 (lines 98,140,161) | {COMMITS.get('1.1.5.a','?')} |",
    f"| 1.1.5.b | backend/core/ai_safety.py | 1 (line 186) | {COMMITS.get('1.1.5.b','?')} |",
    f"| 1.1.5.c | backend/core/llm_router.py | 3 (lines 201,251,258) | {COMMITS.get('1.1.5.c','?')} |",
    f"| 1.1.5.d | backend/health/checker.py | 4 (lines 162,493,646,992) | {COMMITS.get('1.1.5.d','?')} |",
    f"| 1.1.5.e | backend/health/managed_services.py | 2 (lines 73,113) | {COMMITS.get('1.1.5.e','?')} |",
    f"| 1.1.5.f | backend/health/source_checker.py | 2 (lines 54,245) | {COMMITS.get('1.1.5.f','?')} |",
    f"| 1.1.5.g | backend/infra/registry.py | 3 (lines 142,284,300) | {COMMITS.get('1.1.5.g','?')} |",
    f"| 1.1.5.h | backend/manifests/executor.py | 5 (lines 608,723,994,1151,1222) | {COMMITS.get('1.1.5.h','?')} |",
    f"| 1.1.5.i | backend/platform/storage.py | 3 (lines 363,394,400) | {COMMITS.get('1.1.5.i','?')} |",
    "",
    "- `ms-enforce --fast`: Tier 0 `bare-db-commit` → 0 violations. 2 pre-existing violations (1.1.5.j `generated-code-no-ast-verify`, 1.1.5.k `test-hardcodes-data-path`) remain — deferred to OPUS (per plan).",
    "- `pytest tests/test_comprehensive_contracts.py`: 150 passed, 3 pre-existing failures (unchanged from baseline).",
    "- Sub-tasks 1.1.5.j and 1.1.5.k: OPUS-flagged, deferred. See TODO file if not yet triaged.",
    "",
]

record_block = "\n".join(record_lines)

# Mark all 1.1.5 sub-tasks as done (a-i, l, m, n — j/k remain for OPUS)
md_new = md_text
for sub in ['a','b','c','d','e','f','g','h','i','l','m','n']:
    md_new = md_new.replace(
        f"- [ ] **1.1.5.{sub}",
        f"- [x] **1.1.5.{sub}"
    )

# Insert record before the last "---" or at the end of RECORD section
if "**Step 1.1.5" not in md_new:
    # Find insertion point — after the last "**Step 1.1" entry in RECORD
    insert_marker = "**Step 1.2.a — mypy strategy**"
    if insert_marker in md_new:
        md_new = md_new.replace(insert_marker,
            record_block.strip() + "\n\n" + insert_marker)

cleanup_md.write_text(md_new)
ok("PROJECT_CLEANUP.md updated with RECORD and sub-task checkboxes")

# Update STATUS section
md_new2 = cleanup_md.read_text()
md_new2 = md_new2.replace(
    "**Next action:** Sonnet executes step 1.1.5",
    "**Next action:** OPUS triages 1.1.5.j and 1.1.5.k. Then 1.2.b (mypy backfill) can begin"
)
md_new2 = md_new2.replace(
    "**Current Step:** 1.2 (Static Type Checking)",
    "**Current Step:** 1.2 (Static Type Checking) — unblocked after 1.1.5.j/k OPUS triage"
)
cleanup_md.write_text(md_new2)

git_commit("1.1.5.n",
    "docs(cleanup): 1.1.5.n mark step 1.1.5 complete in PROJECT_CLEANUP.md\n\n"
    "All 9 files cleaned (26 db._c.commit() removals), RECORD updated with commit hashes.\n"
    "1.1.5.j and 1.1.5.k remain for OPUS triage (deferred per plan).\n"
    "Tier 0 bare-db-commit violations: 0. Pre-existing unrelated: 2 (j/k).")

# ══════════════════════════════════════════════════════════════════════════════
# Summary
# ══════════════════════════════════════════════════════════════════════════════
heading("COMPLETE — Commit summary")
for label, sha in COMMITS.items():
    print(f"  {sha}  {label}")

print("""
Next steps:
  1. OPUS triages 1.1.5.j (ms-testgen:581 generated-code-no-ast-verify)
     and 1.1.5.k (ms-test.py:1669 test-hardcodes-data-path)
  2. Once j/k settled → push origin main
  3. Then 1.2.b (mypy backfill) can begin
  4. Do NOT push until j/k are settled (or explicitly deferred to TODO)

To push when ready:  git push origin main
""")
