"""Tests for the check_provenance gate in ms-enforce (batch-11 S8, BACKLOG :53).

Exercises both the RED-PATH (missing header → DRIFT verdict in output) and
the clean path (all covered files have provenance headers).

The gate is embedded in ms-enforce; we test it by importing the function
directly using importlib so we don't need to put ms-enforce on sys.path.
"""
from __future__ import annotations

import importlib.machinery
import importlib.util
import json
import sys
from pathlib import Path

import pytest

# ---------------------------------------------------------------------------
# Module loader — pull in ms-enforce without polluting sys.path
# ms-enforce has no .py extension; use SourceFileLoader explicitly.
# ---------------------------------------------------------------------------

_REPO = Path(__file__).resolve().parent.parent
_SCRIPT = _REPO / "ms-enforce"


def _load_module():
    loader = importlib.machinery.SourceFileLoader("ms_enforce", str(_SCRIPT))
    spec = importlib.util.spec_from_file_location(
        "ms_enforce", _SCRIPT, loader=loader
    )
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    sys.modules["ms_enforce"] = mod
    spec.loader.exec_module(mod)
    return mod


_mod = _load_module()
check_provenance = _mod.check_provenance


# ---------------------------------------------------------------------------
# Helpers — temporarily monkey-patch the REPO constant in ms_enforce
# ---------------------------------------------------------------------------

class _FakeRepo:
    """Context manager that replaces ms_enforce.REPO with a tmp_path."""
    def __init__(self, tmp: Path):
        self._tmp = tmp
        self._orig = None

    def __enter__(self):
        self._orig = _mod.REPO
        _mod.REPO = self._tmp
        return self._tmp

    def __exit__(self, *_):
        _mod.REPO = self._orig


# ---------------------------------------------------------------------------
# RED-PATH tests — missing header → DRIFT in output
# ---------------------------------------------------------------------------

class TestProvenanceRedPath:
    def test_json_missing_generated_by_emits_drift(self, tmp_path: Path):
        """A .linecount-baseline.json without 'generated_by' → DRIFT."""
        baseline = tmp_path / ".linecount-baseline.json"
        baseline.write_text(json.dumps({"caps": {}, "files": []}))

        with _FakeRepo(tmp_path):
            passed, detail = check_provenance()

        assert passed is True  # warn-only: always True
        assert "DRIFT" in detail
        assert ".linecount-baseline.json" in detail
        assert "generated_by" in detail

    def test_lockfile_missing_header_emits_drift(self, tmp_path: Path):
        """A uv.lock without '# AUTO-GENERATED' in first 5 lines → DRIFT."""
        lockfile = tmp_path / "uv.lock"
        lockfile.write_text(
            "version = 1\nrevision = 3\nrequires-python = '>=3.12'\n"
        )

        with _FakeRepo(tmp_path):
            passed, detail = check_provenance()

        assert passed is True
        assert "DRIFT" in detail
        assert "uv.lock" in detail
        assert "AUTO-GENERATED" in detail

    def test_json_with_generated_by_is_clean(self, tmp_path: Path):
        """A .linecount-baseline.json WITH 'generated_by' passes cleanly."""
        baseline = tmp_path / ".linecount-baseline.json"
        baseline.write_text(
            json.dumps({
                "generated_by": "tools/check_linecount.py",
                "caps": {},
                "files": [],
            })
        )

        with _FakeRepo(tmp_path):
            passed, detail = check_provenance()

        assert passed is True
        # This file is clean; DRIFT must not appear for it
        # (other covered files are INDETERMINATE since they don't exist in tmp)
        assert "DRIFT: .linecount-baseline.json" not in detail

    def test_lockfile_with_header_is_clean(self, tmp_path: Path):
        """A uv.lock WITH '# AUTO-GENERATED' in first 5 lines passes cleanly."""
        lockfile = tmp_path / "uv.lock"
        lockfile.write_text(
            "# AUTO-GENERATED by uv — do not edit by hand\n"
            "version = 1\nrevision = 3\nrequires-python = '>=3.12'\n"
        )

        with _FakeRepo(tmp_path):
            passed, detail = check_provenance()

        assert passed is True
        assert "DRIFT: uv.lock" not in detail

    def test_absent_file_is_indeterminate_not_drift(self, tmp_path: Path):
        """A covered file that simply doesn't exist → INDETERMINATE, not DRIFT."""
        # tmp_path is empty; no covered files exist
        with _FakeRepo(tmp_path):
            passed, detail = check_provenance()

        assert passed is True
        # None of the absent files should be reported as DRIFT
        assert "DRIFT" not in detail
        assert "INDETERMINATE" in detail

    def test_always_returns_true(self, tmp_path: Path):
        """check_provenance is warn-only — always returns True regardless of DRIFTs."""
        # Plant a broken baseline to force DRIFTs
        (tmp_path / ".linecount-baseline.json").write_text("{}")
        (tmp_path / "uv.lock").write_text("no header here\n")

        with _FakeRepo(tmp_path):
            passed, _detail = check_provenance()

        assert passed is True
