"""tests/test_rules_migration_batch1.py

Mechanical enforcement of CLAUDE.md rules migrated from prose to tests (S-55 Stream B).

NOTE ON WHERE THESE TESTS RUN
-------------------------------
These invariant tests are executed by the `test.yml` GitHub Actions workflow
(job: `pytest tests/ -q ...`), NOT by `ms-enforce`. This distinction matters:
- `ms-enforce` runs locally as a pre-commit / CI gate on lint/schema rules.
- This file (and the broader `tests/` suite) runs in CI via `test.yml`.
If you need to verify these invariants locally, run:
    python3 -m pytest tests/test_rules_migration_batch1.py -q

Rules mechanized here:
  R1: _SLOP_MANAGED_VARS is a module-level frozenset in backend/api/apps.py
      containing the canonical wizard-managed vars (PUID, PGID, TZ, DOMAIN,
      CONFIG_ROOT, MEDIA_ROOT, POSTGRES_PASSWORD, POSTGRES_USER).
      Source: "Project facts — _SLOP_MANAGED_VARS" section of CLAUDE.md.

  R2: AGENT_ROLE = "executive_manager" constant in backend/core/agent.py.
      Source: "Project facts — SLOP AI Agent distinction" section of CLAUDE.md.

  R3: get_all_apps(include_system=False) excludes tier=0 entries from
      user-facing lists.
      Source: "Project facts — SLOP AI Agent distinction" section of CLAUDE.md.

  R4: Any field returned by to_catalog_entry() is also present in the Pydantic
      CatalogEntry model in backend/api/catalog.py — FastAPI silently drops
      fields not in the response model.
      Source: "Project facts — Catalog entry shape" section of CLAUDE.md.
      Updated (batch-11 S9): checks union over ALL manifests, not just first.

  R5: _DEFAULT_STACKS in backend/api/platform.py references only valid catalog
      app keys (every key exists as catalog/apps/<key>.yaml).
      Source: "Project facts — Quick Stacks" section of CLAUDE.md.

  R6: Catalog app web_port values are unique across all manifests, with an
      explicit allowlist for ports that are intentionally shared (Traefik-
      managed system ports that apps don't bind directly as host ports).
      Source: CLAUDE.md + test.yml "Check for port conflicts" step.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))


# ---------------------------------------------------------------------------
# R1: _SLOP_MANAGED_VARS
# ---------------------------------------------------------------------------


class TestSlopManagedVars:
    """_SLOP_MANAGED_VARS is a frozenset containing canonical wizard-managed vars."""

    def test_is_frozenset(self):
        from backend.api.apps import _SLOP_MANAGED_VARS
        assert isinstance(_SLOP_MANAGED_VARS, frozenset), (
            "_SLOP_MANAGED_VARS must be a frozenset — it is the enforcement contract "
            "that prevents linter false positives for wizard-managed env vars"
        )

    def test_contains_core_wizard_vars(self):
        """Canonical vars listed in CLAUDE.md 'Project facts — _SLOP_MANAGED_VARS'."""
        from backend.api.apps import _SLOP_MANAGED_VARS
        required = {"PUID", "PGID", "TZ", "DOMAIN", "CONFIG_ROOT", "MEDIA_ROOT"}
        missing = required - _SLOP_MANAGED_VARS
        assert not missing, (
            f"_SLOP_MANAGED_VARS is missing canonical wizard vars: {missing!r}. "
            "These are always written to .env by the wizard and must be suppressed "
            "from the unknown-var linter."
        )

    def test_contains_postgres_vars(self):
        """POSTGRES_PASSWORD + POSTGRES_USER were explicitly added per session 14."""
        from backend.api.apps import _SLOP_MANAGED_VARS
        for var in ("POSTGRES_PASSWORD", "POSTGRES_USER"):
            assert var in _SLOP_MANAGED_VARS, (
                f"{var!r} must be in _SLOP_MANAGED_VARS — "
                "it is generated by the setup wizard on every SLOP install "
                "(CLAUDE.md: 'Catalog template variables' section)."
            )

    def test_module_level_location(self):
        """_SLOP_MANAGED_VARS must live at module level in backend/api/apps.py."""
        import ast
        apps_py = Path(__file__).resolve().parent.parent / "backend" / "api" / "apps.py"
        tree = ast.parse(apps_py.read_text(encoding="utf-8"))
        top_level_assigns = [
            node for node in ast.walk(tree)
            if isinstance(node, ast.AnnAssign)
            and isinstance(node.target, ast.Name)
            and node.target.id == "_SLOP_MANAGED_VARS"
            and node.col_offset == 0
        ]
        assert top_level_assigns, (
            "_SLOP_MANAGED_VARS must be a module-level annotated assignment in "
            "backend/api/apps.py. If moved, update _SLOP_MANAGED_VARS references "
            "and this test."
        )


# ---------------------------------------------------------------------------
# R2: AGENT_ROLE constant
# ---------------------------------------------------------------------------


class TestAgentRoleConstant:
    """AGENT_ROLE = 'executive_manager' constant in backend/core/agent.py."""

    def test_agent_role_value(self):
        from backend.core.agent import AGENT_ROLE
        assert AGENT_ROLE == "executive_manager", (
            f"AGENT_ROLE must be 'executive_manager', got {AGENT_ROLE!r}. "
            "This constant is the authoritative role identifier for the SLOP Agent "
            "(CLAUDE.md 'Project facts — SLOP AI Agent distinction')."
        )

    def test_agent_key_value(self):
        """AGENT_KEY must be 'slop_agent' — the DB primary identifier."""
        from backend.core.agent import AGENT_KEY
        assert AGENT_KEY == "slop_agent", (
            f"AGENT_KEY must be 'slop_agent', got {AGENT_KEY!r}. "
            "Changing this breaks all DB queries and health API lookups."
        )

    def test_agent_tier_is_zero(self):
        """AGENT_TIER must be 0 — tier-0 = system component, excluded from user lists."""
        from backend.core.agent import AGENT_TIER
        assert AGENT_TIER == 0, (
            f"AGENT_TIER must be 0, got {AGENT_TIER!r}. "
            "Tier 0 is the sentinel that get_all_apps(include_system=False) filters on."
        )

    def test_agent_category_value(self):
        """AGENT_CATEGORY must be 'agent' — segregated from catalog apps."""
        from backend.core.agent import AGENT_CATEGORY
        assert AGENT_CATEGORY == "agent", (
            f"AGENT_CATEGORY must be 'agent', got {AGENT_CATEGORY!r}."
        )

    def test_agent_subject_type_value(self):
        """AGENT_SUBJECT_TYPE must be 'agent' — never 'app' (health check segregation)."""
        from backend.core.agent import AGENT_SUBJECT_TYPE
        assert AGENT_SUBJECT_TYPE == "agent", (
            f"AGENT_SUBJECT_TYPE must be 'agent', got {AGENT_SUBJECT_TYPE!r}. "
            "Mixing with 'app' subject_type would corrupt health check queries."
        )


# ---------------------------------------------------------------------------
# R3: get_all_apps excludes tier=0
# ---------------------------------------------------------------------------


class TestGetAllAppsExcludesSystem:
    """get_all_apps(include_system=False) excludes tier-0 system entries."""

    def test_tier0_excluded_by_default(self, test_db):
        """A tier-0 app seeded in DB must not appear in default get_all_apps()."""
        from backend.core.state import StateDB

        with StateDB() as db:
            # Seed a tier-0 system app (simulating ensure_agent_registered())
            db.upsert_app(
                "test_system_agent",
                display_name="Test System Agent",
                tier=0,
                category="agent",
                status="running",
                image="",
                image_tag="",
                container_name="test_system_agent",
                manifest_source="system",
            )
            # include_system defaults to False
            apps = db.get_all_apps()

        keys = [a.key for a in apps]
        assert "test_system_agent" not in keys, (
            "tier=0 app must NOT appear in get_all_apps() without include_system=True. "
            "This is the contract that prevents the SLOP Agent from appearing in "
            "user-facing app lists and Docker status queries."
        )

    def test_tier0_included_when_requested(self, test_db):
        """get_all_apps(include_system=True) MUST include tier-0 entries."""
        from backend.core.state import StateDB

        with StateDB() as db:
            db.upsert_app(
                "test_system_agent",
                display_name="Test System Agent",
                tier=0,
                category="agent",
                status="running",
                image="",
                image_tag="",
                container_name="test_system_agent",
                manifest_source="system",
            )
            apps = db.get_all_apps(include_system=True)

        keys = [a.key for a in apps]
        assert "test_system_agent" in keys, (
            "tier=0 app must appear when get_all_apps(include_system=True) is called."
        )

    def test_tier2_always_included(self, test_db):
        """Regular tier-2 catalog apps always appear in get_all_apps()."""
        from backend.core.state import StateDB

        with StateDB() as db:
            db.upsert_app(
                "test_regular_app",
                display_name="Test Regular App",
                tier=2,
                category="arr",
                status="running",
                image="someimage",
                image_tag="latest",
                container_name="test_regular_app",
                manifest_source="catalog",
            )
            apps = db.get_all_apps()

        keys = [a.key for a in apps]
        assert "test_regular_app" in keys


# ---------------------------------------------------------------------------
# R4: to_catalog_entry() fields match CatalogEntry Pydantic model
# ---------------------------------------------------------------------------


class TestCatalogEntryFieldSync:
    """to_catalog_entry() fields must all appear in the CatalogEntry Pydantic model.

    FastAPI silently drops fields present in the dict but absent from the
    response_model. This is the highest blast-radius silent failure in the
    catalog API — a new field added to to_catalog_entry() but not CatalogEntry
    simply vanishes from API responses with no error.
    """

    def test_all_to_catalog_entry_keys_present_in_pydantic_model(self):
        """Every key returned by to_catalog_entry() must be a field in CatalogEntry.

        Checks the UNION of keys across ALL manifests (not just the first) so
        that a manifest with an unusual field set can't slip through unnoticed.
        Updated batch-11 S9 from first-only to union-over-all.
        """
        from backend.api.catalog import CatalogEntry
        from backend.manifests.loader import load_all_manifests

        manifests = load_all_manifests()
        assert manifests, "load_all_manifests() returned empty dict — catalog not found"

        pydantic_fields = set(CatalogEntry.model_fields.keys())
        # Union of all keys across every manifest's to_catalog_entry() output.
        all_entry_keys: set[str] = set()
        for m in manifests.values():
            all_entry_keys |= set(m.to_catalog_entry().keys())

        missing_from_pydantic = all_entry_keys - pydantic_fields
        assert not missing_from_pydantic, (
            f"Fields returned by to_catalog_entry() are NOT in CatalogEntry Pydantic model "
            f"and will be silently dropped by FastAPI: {missing_from_pydantic!r}. "
            "Add these fields to CatalogEntry in backend/api/catalog.py. "
            "(CLAUDE.md: 'Catalog entry shape split across two artefacts')"
        )

    def test_pydantic_model_can_consume_entry_dict(self):
        """CatalogEntry(**to_catalog_entry()) must not raise a validation error."""
        from backend.api.catalog import CatalogEntry
        from backend.manifests.loader import load_all_manifests

        manifests = load_all_manifests()
        errors = []
        for key, m in manifests.items():
            try:
                CatalogEntry(**m.to_catalog_entry())
            except Exception as exc:
                errors.append(f"{key}: {exc}")

        assert not errors, (
            "CatalogEntry(**to_catalog_entry()) validation failed for manifests:\n"
            + "\n".join(f"  {e}" for e in errors[:10])
        )


# ---------------------------------------------------------------------------
# R5: _DEFAULT_STACKS references valid catalog app keys
# ---------------------------------------------------------------------------


class TestDefaultStacksReferentialIntegrity:
    """_DEFAULT_STACKS in backend/api/platform.py must reference only valid catalog keys.

    A key in _DEFAULT_STACKS that has no corresponding YAML manifest in
    catalog/apps/ will cause a silent install failure when the user picks that
    stack — the missing key is skipped without feedback.

    Source: CLAUDE.md "Quick Stacks — _DEFAULT_STACKS in backend/api/platform.py
    is the single source of truth."
    """

    def test_default_stacks_keys_exist_in_catalog(self):
        """Every app_key in every _DEFAULT_STACKS entry must exist as catalog/apps/<key>.yaml."""
        from backend.api.platform import _DEFAULT_STACKS

        catalog_dir = Path(__file__).resolve().parent.parent / "catalog" / "apps"
        catalog_keys = {p.stem for p in catalog_dir.glob("*.yaml")}
        assert catalog_keys, "catalog/apps/ is empty — can't validate _DEFAULT_STACKS"

        missing: list[str] = []
        for stack in _DEFAULT_STACKS:
            stack_id = stack.get("id", "<unknown>")
            for key in stack.get("app_keys", []):
                if key not in catalog_keys:
                    missing.append(f"{stack_id}: {key!r}")

        assert not missing, (
            "_DEFAULT_STACKS references catalog app keys that have no YAML manifest:\n"
            + "\n".join(f"  {m}" for m in missing)
            + "\nEither add the missing manifest to catalog/apps/ or remove the key "
            "from _DEFAULT_STACKS in backend/api/platform.py."
        )

    def test_default_stacks_structure(self):
        """Every entry in _DEFAULT_STACKS must have id, label, app_keys, ram_note, ram_gb."""
        from backend.api.platform import _DEFAULT_STACKS

        required_fields = {"id", "label", "app_keys", "ram_note", "ram_gb"}
        errors: list[str] = []
        for i, stack in enumerate(_DEFAULT_STACKS):
            missing_fields = required_fields - set(stack.keys())
            if missing_fields:
                errors.append(
                    f"_DEFAULT_STACKS[{i}] (id={stack.get('id', '?')!r}) "
                    f"missing fields: {missing_fields!r}"
                )
            if not isinstance(stack.get("app_keys", None), list):
                errors.append(
                    f"_DEFAULT_STACKS[{i}] (id={stack.get('id', '?')!r}) "
                    "app_keys must be a list"
                )

        assert not errors, (
            "_DEFAULT_STACKS entries have structural problems:\n"
            + "\n".join(f"  {e}" for e in errors)
        )


# ---------------------------------------------------------------------------
# R6: Catalog host-port uniqueness (with intended-collision allowlist)
# ---------------------------------------------------------------------------


class TestCatalogHostPortUniqueness:
    """Catalog app web_port values must be unique across all manifests.

    Ports on the SYSTEM_PORTS allowlist are intentionally shared — they are
    Traefik-managed ports (80, 443, 8080, 8081) that apps don't bind directly
    as host ports; Traefik owns those ports and proxies to the app containers.

    This test mirrors the 'Check for port conflicts' step in .github/workflows/test.yml
    but lives here so it is also run locally via pytest and its failure message is
    richer. The test.yml step and this test should agree.

    Allowlist rationale (batch-11 S9 — built from reality, not invented):
      - 80:   HTTP — owned by Traefik; filebrowser/freshrss/ntfy/speedtest_tracker/
               vaultwarden all default to internal :80 but Traefik proxies them.
      - 443:  HTTPS — Traefik terminates TLS.
      - 8080: Traefik HTTP entrypoint — Traefik proxies; multiple apps default to
               :8080 internally (bentopdf, dozzle, glance, localai, open_webui,
               scrutiny, stirling_pdf) but are reached via Traefik subdomains.
      - 8081: Traefik alt-HTTP / metrics entrypoint — same pattern.
    """

    # Ports that are intentionally shared across apps because Traefik owns them.
    # Apps on these ports do NOT bind host ports directly — Traefik proxies.
    SYSTEM_PORTS: frozenset[int] = frozenset({80, 443, 8080, 8081})

    def test_non_system_ports_are_unique(self):
        """web_port values outside SYSTEM_PORTS must be unique across all catalog apps."""
        from backend.manifests.loader import load_all_manifests

        manifests = load_all_manifests()
        assert manifests, "load_all_manifests() returned empty dict — catalog not found"

        port_map: dict[int, list[str]] = {}
        for key, m in manifests.items():
            if m.web_port is not None and m.web_port not in self.SYSTEM_PORTS:
                port_map.setdefault(m.web_port, []).append(key)

        conflicts = {p: keys for p, keys in port_map.items() if len(keys) > 1}
        assert not conflicts, (
            "Catalog app web_port collisions found (outside the Traefik system-port "
            "allowlist {80, 443, 8080, 8081}):\n"
            + "\n".join(
                f"  port {p}: {', '.join(sorted(keys))}"
                for p, keys in sorted(conflicts.items())
            )
            + "\nEither assign unique ports or add the port to SYSTEM_PORTS if it is "
            "a Traefik-managed entrypoint that apps don't bind directly."
        )

    def test_system_ports_allowlist_is_not_empty(self):
        """SYSTEM_PORTS allowlist must be non-empty (a fully-empty allowlist is suspicious)."""
        assert self.SYSTEM_PORTS, "SYSTEM_PORTS allowlist is empty — this is likely a bug"
