"""tests/test_rules_migration_batch1.py

Mechanical enforcement of CLAUDE.md rules migrated from prose to tests (S-55 Stream B).

Rules mechanized here:
  R1: _SLOP_MANAGED_VARS is a module-level frozenset in backend/api/apps.py
      containing the canonical wizard-managed vars (PUID, PGID, TZ, DOMAIN,
      CONFIG_ROOT, MEDIA_ROOT, POSTGRES_PASSWORD, POSTGRES_USER).
      Source: "Project facts — _SLOP_MANAGED_VARS" section of CLAUDE.md.

  R2: AGENT_ROLE = "executive_manager" constant in backend/core/agent.py.
      Source: "Project facts — SLOP AI Agent distinction" section of CLAUDE.md.

  R3: get_all_apps(include_system=False) excludes tier=0 entries from
      user-facing lists.
      Source: "Project facts — SLOP AI Agent distinction" section of CLAUDE.md.

  R4: Any field returned by to_catalog_entry() is also present in the Pydantic
      CatalogEntry model in backend/api/catalog.py — FastAPI silently drops
      fields not in the response model.
      Source: "Project facts — Catalog has two CatalogEntry definitions" section
      of CLAUDE.md.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))


# ---------------------------------------------------------------------------
# R1: _SLOP_MANAGED_VARS
# ---------------------------------------------------------------------------


class TestSlopManagedVars:
    """_SLOP_MANAGED_VARS is a frozenset containing canonical wizard-managed vars."""

    def test_is_frozenset(self):
        from backend.api.apps import _SLOP_MANAGED_VARS
        assert isinstance(_SLOP_MANAGED_VARS, frozenset), (
            "_SLOP_MANAGED_VARS must be a frozenset — it is the enforcement contract "
            "that prevents linter false positives for wizard-managed env vars"
        )

    def test_contains_core_wizard_vars(self):
        """Canonical vars listed in CLAUDE.md 'Project facts — _SLOP_MANAGED_VARS'."""
        from backend.api.apps import _SLOP_MANAGED_VARS
        required = {"PUID", "PGID", "TZ", "DOMAIN", "CONFIG_ROOT", "MEDIA_ROOT"}
        missing = required - _SLOP_MANAGED_VARS
        assert not missing, (
            f"_SLOP_MANAGED_VARS is missing canonical wizard vars: {missing!r}. "
            "These are always written to .env by the wizard and must be suppressed "
            "from the unknown-var linter."
        )

    def test_contains_postgres_vars(self):
        """POSTGRES_PASSWORD + POSTGRES_USER were explicitly added per session 14."""
        from backend.api.apps import _SLOP_MANAGED_VARS
        for var in ("POSTGRES_PASSWORD", "POSTGRES_USER"):
            assert var in _SLOP_MANAGED_VARS, (
                f"{var!r} must be in _SLOP_MANAGED_VARS — "
                "it is generated by the setup wizard on every SLOP install "
                "(CLAUDE.md: 'Catalog template variables' section)."
            )

    def test_module_level_location(self):
        """_SLOP_MANAGED_VARS must live at module level in backend/api/apps.py."""
        import ast
        apps_py = Path(__file__).resolve().parent.parent / "backend" / "api" / "apps.py"
        tree = ast.parse(apps_py.read_text(encoding="utf-8"))
        top_level_assigns = [
            node for node in ast.walk(tree)
            if isinstance(node, ast.AnnAssign)
            and isinstance(node.target, ast.Name)
            and node.target.id == "_SLOP_MANAGED_VARS"
            and node.col_offset == 0
        ]
        assert top_level_assigns, (
            "_SLOP_MANAGED_VARS must be a module-level annotated assignment in "
            "backend/api/apps.py. If moved, update _SLOP_MANAGED_VARS references "
            "and this test."
        )


# ---------------------------------------------------------------------------
# R2: AGENT_ROLE constant
# ---------------------------------------------------------------------------


class TestAgentRoleConstant:
    """AGENT_ROLE = 'executive_manager' constant in backend/core/agent.py."""

    def test_agent_role_value(self):
        from backend.core.agent import AGENT_ROLE
        assert AGENT_ROLE == "executive_manager", (
            f"AGENT_ROLE must be 'executive_manager', got {AGENT_ROLE!r}. "
            "This constant is the authoritative role identifier for the SLOP Agent "
            "(CLAUDE.md 'Project facts — SLOP AI Agent distinction')."
        )

    def test_agent_key_value(self):
        """AGENT_KEY must be 'slop_agent' — the DB primary identifier."""
        from backend.core.agent import AGENT_KEY
        assert AGENT_KEY == "slop_agent", (
            f"AGENT_KEY must be 'slop_agent', got {AGENT_KEY!r}. "
            "Changing this breaks all DB queries and health API lookups."
        )

    def test_agent_tier_is_zero(self):
        """AGENT_TIER must be 0 — tier-0 = system component, excluded from user lists."""
        from backend.core.agent import AGENT_TIER
        assert AGENT_TIER == 0, (
            f"AGENT_TIER must be 0, got {AGENT_TIER!r}. "
            "Tier 0 is the sentinel that get_all_apps(include_system=False) filters on."
        )

    def test_agent_category_value(self):
        """AGENT_CATEGORY must be 'agent' — segregated from catalog apps."""
        from backend.core.agent import AGENT_CATEGORY
        assert AGENT_CATEGORY == "agent", (
            f"AGENT_CATEGORY must be 'agent', got {AGENT_CATEGORY!r}."
        )

    def test_agent_subject_type_value(self):
        """AGENT_SUBJECT_TYPE must be 'agent' — never 'app' (health check segregation)."""
        from backend.core.agent import AGENT_SUBJECT_TYPE
        assert AGENT_SUBJECT_TYPE == "agent", (
            f"AGENT_SUBJECT_TYPE must be 'agent', got {AGENT_SUBJECT_TYPE!r}. "
            "Mixing with 'app' subject_type would corrupt health check queries."
        )


# ---------------------------------------------------------------------------
# R3: get_all_apps excludes tier=0
# ---------------------------------------------------------------------------


class TestGetAllAppsExcludesSystem:
    """get_all_apps(include_system=False) excludes tier-0 system entries."""

    def test_tier0_excluded_by_default(self, test_db):
        """A tier-0 app seeded in DB must not appear in default get_all_apps()."""
        from backend.core.state import StateDB

        with StateDB() as db:
            # Seed a tier-0 system app (simulating ensure_agent_registered())
            db.upsert_app(
                "test_system_agent",
                display_name="Test System Agent",
                tier=0,
                category="agent",
                status="running",
                image="",
                image_tag="",
                container_name="test_system_agent",
                manifest_source="system",
            )
            # include_system defaults to False
            apps = db.get_all_apps()

        keys = [a.key for a in apps]
        assert "test_system_agent" not in keys, (
            "tier=0 app must NOT appear in get_all_apps() without include_system=True. "
            "This is the contract that prevents the SLOP Agent from appearing in "
            "user-facing app lists and Docker status queries."
        )

    def test_tier0_included_when_requested(self, test_db):
        """get_all_apps(include_system=True) MUST include tier-0 entries."""
        from backend.core.state import StateDB

        with StateDB() as db:
            db.upsert_app(
                "test_system_agent",
                display_name="Test System Agent",
                tier=0,
                category="agent",
                status="running",
                image="",
                image_tag="",
                container_name="test_system_agent",
                manifest_source="system",
            )
            apps = db.get_all_apps(include_system=True)

        keys = [a.key for a in apps]
        assert "test_system_agent" in keys, (
            "tier=0 app must appear when get_all_apps(include_system=True) is called."
        )

    def test_tier2_always_included(self, test_db):
        """Regular tier-2 catalog apps always appear in get_all_apps()."""
        from backend.core.state import StateDB

        with StateDB() as db:
            db.upsert_app(
                "test_regular_app",
                display_name="Test Regular App",
                tier=2,
                category="arr",
                status="running",
                image="someimage",
                image_tag="latest",
                container_name="test_regular_app",
                manifest_source="catalog",
            )
            apps = db.get_all_apps()

        keys = [a.key for a in apps]
        assert "test_regular_app" in keys


# ---------------------------------------------------------------------------
# R4: to_catalog_entry() fields match CatalogEntry Pydantic model
# ---------------------------------------------------------------------------


class TestCatalogEntryFieldSync:
    """to_catalog_entry() fields must all appear in the CatalogEntry Pydantic model.

    FastAPI silently drops fields present in the dict but absent from the
    response_model. This is the highest blast-radius silent failure in the
    catalog API — a new field added to to_catalog_entry() but not CatalogEntry
    simply vanishes from API responses with no error.
    """

    def test_all_to_catalog_entry_keys_present_in_pydantic_model(self):
        """Every key returned by to_catalog_entry() must be a field in CatalogEntry."""
        from backend.api.catalog import CatalogEntry
        from backend.manifests.loader import load_all_manifests

        manifests = load_all_manifests()
        assert manifests, "load_all_manifests() returned empty dict — catalog not found"

        # Use first manifest to get a representative to_catalog_entry() output
        first_manifest = next(iter(manifests.values()))
        entry_dict = first_manifest.to_catalog_entry()

        pydantic_fields = set(CatalogEntry.model_fields.keys())
        entry_keys = set(entry_dict.keys())

        missing_from_pydantic = entry_keys - pydantic_fields
        assert not missing_from_pydantic, (
            f"Fields returned by to_catalog_entry() are NOT in CatalogEntry Pydantic model "
            f"and will be silently dropped by FastAPI: {missing_from_pydantic!r}. "
            "Add these fields to CatalogEntry in backend/api/catalog.py. "
            "(CLAUDE.md: 'Catalog has two CatalogEntry definitions')"
        )

    def test_pydantic_model_can_consume_entry_dict(self):
        """CatalogEntry(**to_catalog_entry()) must not raise a validation error."""
        from backend.api.catalog import CatalogEntry
        from backend.manifests.loader import load_all_manifests

        manifests = load_all_manifests()
        errors = []
        for key, m in manifests.items():
            try:
                CatalogEntry(**m.to_catalog_entry())
            except Exception as exc:
                errors.append(f"{key}: {exc}")

        assert not errors, (
            "CatalogEntry(**to_catalog_entry()) validation failed for manifests:\n"
            + "\n".join(f"  {e}" for e in errors[:10])
        )
